apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "intergration-jenkins"
  annotations:
    gitlab.com/project-slug: backstage/integration-jenkins
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: "Backstage/backstage"
spec:
  type: service
  lifecycle: experimental
  owner: "backstage-team-a"
