# template.yaml

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: jenkins-pipeline
  title: Run Jenkins Pipeline
  description: Run Jenkins Pipeline
spec:
  owner: backstage-team-a
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - pipelinename
        - token
      properties:
        pipelinename:
          title: Pipeline name
          type: string
          description: Pipeline name
          ui:autofocus: true
        token:
          title: token
          type: string
          description: token

  steps:
    - id: runJenkinsPipeline
      name: Run Jenkins Pipeline
      action: jenkins:pipeline:run
      input:
        pipelineName: ${{ parameters.pipelinename }}
        token: ${{ parameters.token }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: https://jenkins.publicislabs.net/job/${{pipelineName}}
        catalogInfoUrl: https://github.com/KISLAYA-SRI/backstage/blob/main/jenkins-catalog-info.yaml

output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}

