apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: jenkins-pipeline
  title: Run Jenkins Pipeline
  description: Run Jenkins Pipeline
spec:
  owner: backstage-team-a
  type: service
  tags:
    - jenkins
    - pipeline
  parameters:
    - title: Fill in some steps
      required:
        - pipelinename
        - token
      properties:
        pipelinename:
          title: Pipeline name
          type: string
          description: Pipeline name
          ui:autofocus: true
        key:
          title: Pipeline parameter(key)
          type: string
          description: Parameter for running parameterized pipeline
  steps:
    - id: runJenkinsPipeline
      name: Run Jenkins Pipeline
      action: jenkins:run
      input:
        pipelineName: ${{ parameters.pipelinename }}
        key: ${{ parameters.key }}
